# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from subprocess import call


class Ui_filter(object):
    def setupUi(self, filter):
        filter.setObjectName("filter")
        filter.setFixedSize(718, 402)
        self.label_7 = QtWidgets.QLabel(filter)
        self.label_7.setEnabled(True)
        self.label_7.setGeometry(QtCore.QRect(-10, -10, 731, 411))
        self.label_7.setMaximumSize(QtCore.QSize(731, 411))
        self.label_7.setMouseTracking(False)
        self.label_7.setStyleSheet("background-image: url(:/image/white.jpg);")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/image/white.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(filter)
        self.label_6.setGeometry(QtCore.QRect(320, 10, 81, 71))
        self.label_6.setStyleSheet("background-image: url(:/image/6.png);")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/image/6.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.pushButton_3 = QtWidgets.QPushButton(filter)
        self.pushButton_3.setGeometry(QtCore.QRect(90, 240, 101, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(filter)
        self.label.setGeometry(QtCore.QRect(10, 80, 701, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(filter)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 711, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.pushButton_4 = QtWidgets.QPushButton(filter)
        self.pushButton_4.setGeometry(QtCore.QRect(310, 240, 101, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(filter)
        self.pushButton_5.setGeometry(QtCore.QRect(540, 240, 101, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(filter)
        self.pushButton_6.setGeometry(QtCore.QRect(90, 300, 101, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(filter)
        self.pushButton_7.setGeometry(QtCore.QRect(310, 300, 101, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_7.raise_()
        self.label_6.raise_()
        self.pushButton_3.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_4.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()

        self.retranslateUi(filter)
        QtCore.QMetaObject.connectSlotsByName(filter)

    def retranslateUi(self, filter):
        _translate = QtCore.QCoreApplication.translate
        filter.setWindowTitle(_translate("filter", "Form"))
        self.pushButton_3.setText(_translate("filter", "Moyenne"))
        self.label.setText(_translate("filter", "<html><head/><body><p align=\"center\">Bienvenue dans notre application</p></body></html>"))
        self.label_4.setText(_translate("filter", "<html><head/><body><p align=\"center\">Pour améliorer la qualité de votre image en vous d\'utliser une de ce 3 filtre</p></body></html>"))
        self.pushButton_4.setText(_translate("filter", "Median"))
        self.pushButton_5.setText(_translate("filter", "Mask"))
        self.pushButton_6.setText(_translate("filter", "Cadre"))
        self.pushButton_7.setText(_translate("filter", "N & B"))
        self.pushButton_3.clicked.connect(self.Button_clickede)
        self.pushButton_4.clicked.connect(self.Button_clickede1)
        self.pushButton_5.clicked.connect(self.Button_clickede2)
        self.pushButton_6.clicked.connect(self.Button_clickede3)
        self.pushButton_7.clicked.connect(self.Button_clickede4)

    def Button_clickede1(self):
            filter.destroy()
            call(["python", "median.py"])

    def Button_clickede(self):
            filter.destroy()
            call(["python", "moyeneur.py"])
    def Button_clickede2(self):
            filter.destroy()
            call(["python", "mask.py"])
    def Button_clickede3(self):
            filter.destroy()
            call(["python", "cadre.py"])
    def Button_clickede4(self):
            filter.destroy()
            call(["python", "nb.py"])


            
import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    filter = QtWidgets.QWidget()
    ui = Ui_filter()
    ui.setupUi(filter)
    filter.show()
    sys.exit(app.exec_())
